import { createClient } from "npm:@supabase/supabase-js@2";
import webpush from "npm:web-push@3.6.7";

const URL=Deno.env.get('SUPABASE_URL')!, SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!, ANON=Deno.env.get('SUPABASE_ANON_KEY')!;
const VAPID_PUBLIC=Deno.env.get('VAPID_PUBLIC_KEY')!,VAPID_PRIVATE=Deno.env.get('VAPID_PRIVATE_KEY')!,VAPID_SUBJECT=Deno.env.get('VAPID_SUBJECT')!;
const ADMIN_EMAILS=(Deno.env.get('ICC_ADMIN_EMAILS')||'corineallany@gmail.com').toLowerCase().split(',').map(x=>x.trim()).filter(Boolean);
const admin=createClient(URL,SERVICE), cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Content-Type':'application/json'};
const json=(x:any,status=200)=>new Response(JSON.stringify(x),{status,headers:cors});
const norm=(x:any)=>String(x??'').trim().toLowerCase(),time=(x:any)=>Date.parse(x?.updatedAt||x?.updated_at||x?.deletedAt||x?.archivedAt||0)||0;
function entities(a:any[]=[],b:any[]=[],key:(x:any)=>string){const m=new Map<string,any>();for(const arr of[a,b])for(const x of arr||[]){if(!x)continue;const k=String(key(x)||'');if(!k)continue;const old=m.get(k);if(!old||time(x)>=time(old))m.set(k,x)}return[...m.values()]}
function mergeState(a:any={},b:any={}){const mergePurged=(x:any[]=[],y:any[]=[])=>{const m=new Map<string,any>();for(const arr of[x,y])for(const t of arr||[]){const o=typeof t==='string'?{id:t,at:'1970-01-01T00:00:00.000Z'}:t;if(!o?.id)continue;const old=m.get(String(o.id));if(!old||Date.parse(o.at||0)>=Date.parse(old.at||0))m.set(String(o.id),o)}return[...m.values()]};const purged={members:mergePurged(a.purged?.members,b.purged?.members),programs:mergePurged(a.purged?.programs,b.purged?.programs),solicitations:mergePurged(a.purged?.solicitations,b.purged?.solicitations),models:mergePurged(a.purged?.models,b.purged?.models),poles:mergePurged(a.purged?.poles,b.purged?.poles)};const ids=(k:keyof typeof purged)=>new Set(purged[k].map((x:any)=>String(x.id)));const out:any={...a,...b,purged};out.settings={...(a.settings||{}),...(b.settings||{})};out.settings.permissions={...(a.settings?.permissions||{}),...(b.settings?.permissions||{})};out.settings.poleMeta={...(a.settings?.poleMeta||{}),...(b.settings?.poleMeta||{})};const purgedPoleIds=new Set((purged.poles||[]).map((x:any)=>norm(x.id)));out.poles=[...new Set([...(a.poles||[]),...(b.poles||[])].map((x:any)=>String(x).trim()).filter(Boolean))].filter((x:any)=>!purgedPoleIds.has(norm(x)));out.members=entities(a.members,b.members,(x:any)=>x.id||norm(x.loginEmail||x.email)||x.name).filter((x:any)=>!ids('members').has(String(x.id)));out.programs=entities(a.programs,b.programs,(x:any)=>x.id||`${x.title}|${x.start}`).filter((x:any)=>!ids('programs').has(String(x.id)));out.solicitations=entities(a.solicitations,b.solicitations,(x:any)=>x.id||`${x.event||x.title}|${x.date}`).filter((x:any)=>!ids('solicitations').has(String(x.id)));out.evaluations=entities(a.evaluations,b.evaluations,(x:any)=>x.id);out.postReviews={...(a.postReviews||{}),...(b.postReviews||{})};out.pilotage={models:entities(a.pilotage?.models,b.pilotage?.models,(x:any)=>x.id).filter((x:any)=>!ids('models').has(String(x.id))),availability:entities(a.pilotage?.availability,b.pilotage?.availability,(x:any)=>x.id),audit:entities(a.pilotage?.audit,b.pilotage?.audit,(x:any)=>x.id),checklists:{...(a.pilotage?.checklists||{}),...(b.pilotage?.checklists||{})}};out.schemaVersion=110;out.updatedAt=new Date().toISOString();return out}
async function userFrom(req:Request){const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))return null;const c=createClient(URL,ANON,{global:{headers:{Authorization:auth}}});const{data,error}=await c.auth.getUser();return error?null:data.user}
async function accessFor(user:any){if(!user)return null;if(ADMIN_EMAILS.includes(norm(user.email)))return{role:'responsable',member_id:null,active:true,admin:true};const{data}=await admin.from('icc_user_access').select('*').eq('user_id',user.id).eq('active',true).maybeSingle();return data||null}
async function stateRow(){const{data,error}=await admin.from('icc_app_state').select('data,revision,updated_at').eq('id','main').maybeSingle();if(error)throw error;return data||{data:{},revision:0,updated_at:null}}
async function linkProfile(user:any){const row=await stateRow(),members=Array.isArray(row.data?.members)?row.data.members:[];let m=members.find((x:any)=>String(x.authUserId||x.user_id||'')===user.id)||members.find((x:any)=>norm(x.loginEmail||x.email)===norm(user.email));const isAdmin=ADMIN_EMAILS.includes(norm(user.email));if(m&&!m.authUserId){m.authUserId=user.id;m.updatedAt=new Date().toISOString();const merged=mergeState(row.data,{members});await admin.from('icc_app_state').update({data:merged,updated_at:new Date().toISOString(),updated_by:user.id}).eq('id','main')}if(m||isAdmin){const row={user_id:user.id,email:norm(user.email),member_id:m?.id||null,role:isAdmin?'responsable':(m?.role||'equipier'),active:true,updated_at:new Date().toISOString()};const{data:existing}=await admin.from('icc_user_access').select('id').eq('user_id',user.id).order('id',{ascending:true}).limit(1).maybeSingle();if(existing?.id)await admin.from('icc_user_access').update(row).eq('id',existing.id);else await admin.from('icc_user_access').insert(row)}return{member:m||null,role:isAdmin?'responsable':(m?.role||'equipier'),admin:isAdmin}}
function recipientsForSolicitation(s:any,members:any[]){const ids=new Set<string>();for(const t of s?.targets||[]){if(t.type==='person')ids.add(String(t.value));else if(t.type==='pole')members.filter((m:any)=>(m.poles||[]).includes(t.value)&&!m.deletedAt).forEach((m:any)=>ids.add(String(m.id)));else if(t.type==='com')members.filter((m:any)=>m.status!=='inactive'&&!m.deletedAt).forEach((m:any)=>ids.add(String(m.id)))}return[...ids]}
function recipientsForProgram(p:any){const ids=new Set<string>((p?.memberIds||[]).map(String));for(const a of Object.values(p?.assignments||{}) as any[])for(const id of a?.memberIds||[])ids.add(String(id));return[...ids]}
async function sendTo(memberIds:string[],message:any,userId?:string){let q=admin.from('icc_push_subscriptions').select('id,user_id,member_id,subscription').eq('enabled',true);if(userId)q=q.eq('user_id',userId);else if(memberIds.length)q=q.in('member_id',memberIds);const{data,error}=await q;if(error)throw error;let sent=0,failed=0;for(const row of data||[]){try{await webpush.sendNotification(row.subscription,JSON.stringify(message));sent++}catch(e:any){failed++;if([404,410].includes(e?.statusCode))await admin.from('icc_push_subscriptions').update({enabled:false,updated_at:new Date().toISOString()}).eq('id',row.id)}}return{sent,failed}}

function parisParts(date=new Date()){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date);const g=(t:string)=>p.find(x=>x.type===t)?.value||'';return{date:`${g('year')}-${g('month')}-${g('day')}`,hour:Number(g('hour')),minute:Number(g('minute'))}}
function localDay(s:string){const[y,m,d]=String(s||'').slice(0,10).split('-').map(Number);return y&&m&&d?new Date(y,m-1,d,12):null}
function occurs(p:any,date:string){const d=localDay(date),s=localDay(p.start);if(!d||!s||d<s)return false;const r=p.recurrence||{type:'ponctuel'},type=typeof r==='string'?r:(r.type||'ponctuel');if(r.until&&date>r.until)return false;if(type==='ponctuel')return date===String(p.start||'').slice(0,10);if(type==='annuel')return d.getMonth()===s.getMonth()&&d.getDate()===s.getDate();const wd=Number(r.weekday??s.getDay());if(type==='hebdo')return d.getDay()===wd;if(type==='bihebdo'){if(d.getDay()!==wd)return false;let first=new Date(s);if(first.getDay()!==wd)first.setDate(first.getDate()+((wd-first.getDay()+7)%7));return Math.round((d.getTime()-first.getTime())/86400000)%14===0}const md=Number(r.monthDay||s.getDate());const months=(d.getFullYear()-s.getFullYear())*12+d.getMonth()-s.getMonth();if(type==='mensuel')return d.getDate()===md;if(type==='bimensuel')return d.getDate()===md&&months%2===0;if(type==='trimestriel')return d.getDate()===md&&months%3===0;return false}
async function processReminders(){const row=await stateRow(),state=row.data||{},members=state.members||[],now=parisParts(),mins=now.hour*60+now.minute,programs=(state.programs||[]).filter((p:any)=>!p.archivedAt&&!p.deletedAt&&p.status!=='cancelled'&&p.startTime&&occurs(p,now.date));let sent=0,failed=0,checked=0;for(const p of programs){const[h,m]=String(p.startTime).split(':').map(Number),delta=h*60+m-mins;if(delta<45||delta>75)continue;checked++;const{data:already}=await admin.from('icc_push_reminders').select('id').eq('program_id',p.id).eq('occurrence_date',now.date).eq('reminder_type','one_hour').maybeSingle();if(already)continue;const ids=recipientsForProgram(p);const r=await sendTo(ids,{title:'Rappel de programme',body:`${p.title}${p.startTime?' à '+p.startTime:''} — soyez à l’heure.`,url:'./?open=programmes',tag:`reminder-${p.id}-${now.date}`});sent+=r.sent;failed+=r.failed;await admin.from('icc_push_reminders').insert({program_id:p.id,occurrence_date:now.date,reminder_type:'one_hour',sent_at:new Date().toISOString(),targets:ids.length})}return{sent,failed,checked}}

Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const body=await req.json().catch(()=>({}));if(body.action==='public-key')return json({success:true,publicKey:VAPID_PUBLIC});if(body.action==='process-reminders'){webpush.setVapidDetails(VAPID_SUBJECT,VAPID_PUBLIC,VAPID_PRIVATE);return json({success:true,...await processReminders()})}const user=await userFrom(req);if(!user)return json({success:false,error:'Non authentifié'},401);
if(body.action==='profile-link')return json({success:true,...await linkProfile(user)});
/* Tout compte Supabase authentifié partage la même base COM Le Mans.
   Les droits métier restent contrôlés dans l'application. */
if(body.action==='state-read'){const row=await stateRow();return json({success:true,state:row.data||{},revision:row.revision||0,updated_at:row.updated_at})}
if(body.action==='state-sync'){
  if(!body.state||typeof body.state!=='object')return json({success:false,error:'État invalide'},400);
  const row=await stateRow(),merged=mergeState(row.data||{},body.state);
  const{data,error}=await admin.from('icc_app_state').upsert({
    id:'main',data:merged,updated_at:new Date().toISOString(),updated_by:user.id
  },{onConflict:'id'}).select('data,revision').single();
  if(error)throw error;
  return json({success:true,state:data.data,revision:data.revision});
}
const access=await accessFor(user);
/* Les actions personnelles/push restent possibles même avant liaison de profil.
   member_id pourra être null jusqu'à la liaison. */
if(body.action==='push-subscribe'){const sub=body.subscription;if(!sub?.endpoint)return json({success:false,error:'Abonnement invalide'},400);const profile=await linkProfile(user);const pushRow={user_id:user.id,member_id:profile.member?.id||access?.member_id||null,endpoint:sub.endpoint,subscription:sub,user_agent:body.userAgent||'',enabled:true,updated_at:new Date().toISOString()};const{data:existing}=await admin.from('icc_push_subscriptions').select('id').eq('endpoint',sub.endpoint).order('id',{ascending:true}).limit(1).maybeSingle();if(existing?.id)await admin.from('icc_push_subscriptions').update(pushRow).eq('id',existing.id);else await admin.from('icc_push_subscriptions').insert(pushRow);return json({success:true,member_id:profile.member?.id||access?.member_id||null})}
if(body.action==='push-disable'){await admin.from('icc_push_subscriptions').update({enabled:false,updated_at:new Date().toISOString()}).eq('user_id',user.id).eq('endpoint',body.endpoint);return json({success:true})}
webpush.setVapidDetails(VAPID_SUBJECT,VAPID_PUBLIC,VAPID_PRIVATE);
if(body.action==='test-push'){return json({success:true,...await sendTo([], {title:body.title||'COM Le Mans',body:body.body||'Test notification push',url:body.url||'./'},user.id)})}
if(body.action==='notify-event'){const kind=body.kind,p=body.payload||{},row=await stateRow(),members=row.data?.members||[];let ids:string[]=[],message:any={title:'COM Le Mans',body:'Nouvelle information disponible.',url:'./'};if(kind==='solicitation.created'){ids=recipientsForSolicitation(p.solicitation,members);message={title:'Nouvelle sollicitation',body:p.solicitation?.event||'Une nouvelle sollicitation vous concerne.',url:'./?open=sollicitations'}}else if(['program.created','program.updated'].includes(kind)){ids=recipientsForProgram(p.program);message={title:kind==='program.created'?'Nouveau programme':'Programme modifié',body:p.program?.title||'Un programme vous concerne.',url:'./?open=programmes'}}else if(kind==='solicitation.response'){const creator=p.solicitation?.fromMemberId;if(creator)ids=[String(creator)];else ids=members.filter((m:any)=>['responsable','adjoint'].includes(m.role)).map((m:any)=>String(m.id));message={title:'Réponse à une sollicitation',body:p.solicitation?.event||'Une réponse a été enregistrée.',url:'./?open=sollicitations'}}else return json({success:true,sent:0,failed:0});return json({success:true,...await sendTo(ids,message),targets:ids.length})}
return json({success:false,error:'Action inconnue'},400)}catch(e:any){console.error(e);return json({success:false,error:e?.message||String(e)},500)}});
