(()=>{'use strict';let statusEl=null,keyCache='';const app=()=>window.COMApp;
function b64(s){const p='='.repeat((4-s.length%4)%4),raw=atob((s+p).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
function status(msg,ok=false){if(statusEl){statusEl.textContent=msg;statusEl.className='text-[11px] mt-2 '+(ok?'text-emerald-700':'text-slate-500')}}
async function invoke(action,payload={}){const c=app()?.cloudClient;if(!c)throw new Error('Supabase indisponible.');const{data,error}=await c.functions.invoke('send-push',{body:{action,...payload}});if(error)throw error;if(data?.success===false)throw new Error(data.error||'Erreur notifications');return data||{}}
async function publicKey(){if(keyCache)return keyCache;const d=await invoke('public-key');if(!d.publicKey)throw new Error('Clé VAPID publique indisponible.');return keyCache=d.publicKey}
async function subscription(){if(!('serviceWorker'in navigator)||!('PushManager'in window))throw new Error('Notifications push non disponibles sur cet appareil.');const reg=await navigator.serviceWorker.ready;return{reg,sub:await reg.pushManager.getSubscription()}}
async function enable(){try{if(!app()?.session)throw new Error('Connecte-toi d’abord à ton compte.');if(!('Notification'in window))throw new Error('Notifications non disponibles.');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Autorisation de notifications refusée.');const{reg,sub:existing}=await subscription();const sub=existing||await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(await publicKey())});const d=await invoke('push-subscribe',{subscription:sub.toJSON(),userAgent:navigator.userAgent});status(d.member_id?'Notifications activées et liées au profil ✅':'Notifications activées. Associe ton e-mail à une fiche membre.',true);return true}catch(e){console.warn(e);status(e.message||String(e));alert(e.message||e);return false}}
async function disable(){try{const{reg,sub}=await subscription();void reg;if(sub){await invoke('push-disable',{endpoint:sub.endpoint});await sub.unsubscribe()}status('Notifications désactivées.')}catch(e){status(e.message||String(e))}}
async function rebind(){try{if(!app()?.session)return;const{sub}=await subscription();if(sub&&Notification.permission==='granted')await invoke('push-subscribe',{subscription:sub.toJSON(),userAgent:navigator.userAgent});await refresh()}catch(e){console.warn(e)}}
async function refresh(){try{const{sub}=await subscription();status(sub&&Notification.permission==='granted'?'Notifications téléphone activées ✅':'Notifications téléphone non activées.',!!sub)}catch(e){status('Notifications non disponibles.')}}
async function test(){try{const d=await invoke('test-push',{title:'COM Le Mans',body:'Les notifications fonctionnent ✅',url:'./'});status(`Test : ${d.sent||0} envoyée(s), ${d.failed||0} échec(s).`,(d.sent||0)>0)}catch(e){status(e.message||String(e))}}
function mountSettings(){const slot=document.getElementById('push-settings-slot');if(!slot)return;slot.innerHTML='<div class="border rounded-xl p-4"><div class="flex flex-wrap justify-between gap-3"><div><b class="text-sm text-iccViolet">🔔 Notifications téléphone</b><p class="text-[10px] text-slate-500">Notifications système même quand COM Le Mans est fermée.</p></div><div class="flex gap-2"><button id="push-enable" class="bg-iccYellow text-slate-900 text-xs font-black px-3 py-2 rounded-lg">Activer</button><button id="push-test" class="bg-white border text-xs font-bold px-3 py-2 rounded-lg">Tester</button><button id="push-disable" class="bg-white border text-xs font-bold px-3 py-2 rounded-lg">Désactiver</button></div></div><div id="push-status-final" class="text-[11px] mt-2 text-slate-500"></div></div>';statusEl=document.getElementById('push-status-final');document.getElementById('push-enable').onclick=enable;document.getElementById('push-disable').onclick=disable;document.getElementById('push-test').onclick=test;refresh()}
window.COMPush={enable,disable,rebind,refresh,test,mountSettings};document.addEventListener('DOMContentLoaded',()=>setTimeout(mountSettings,500));})();
