-- COM ICC Le Mans V71 — abonnements Web Push
create table if not exists public.icc_push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  member_id text,
  endpoint text not null unique,
  subscription jsonb not null,
  user_agent text,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists icc_push_subscriptions_user_idx
  on public.icc_push_subscriptions(user_id);

create index if not exists icc_push_subscriptions_member_idx
  on public.icc_push_subscriptions(member_id)
  where enabled = true;

alter table public.icc_push_subscriptions enable row level security;

drop policy if exists "push own select" on public.icc_push_subscriptions;
drop policy if exists "push own insert" on public.icc_push_subscriptions;
drop policy if exists "push own update" on public.icc_push_subscriptions;
drop policy if exists "push own delete" on public.icc_push_subscriptions;

create policy "push own select"
on public.icc_push_subscriptions for select
to authenticated
using (auth.uid() = user_id);

create policy "push own insert"
on public.icc_push_subscriptions for insert
to authenticated
with check (auth.uid() = user_id);

create policy "push own update"
on public.icc_push_subscriptions for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "push own delete"
on public.icc_push_subscriptions for delete
to authenticated
using (auth.uid() = user_id);
